import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to Next.js!</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main>
        <h1>Hello, Next.js!</h1>
        <p>Your app is up and running.</p>
      </main>
    </>
  );
}